defaultPlatforms:
  - linux/arm64
  - linux/amd64
  - linux/s390x
  - linux/ppc64le

builds:
  - id: manager
    main: ./cmd
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
