apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: github-token-manager
    app.kubernetes.io/part-of: github-token-manager
    app.kubernetes.io/managed-by: kustomize
  name: manager-metrics-service
  namespace: system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: manager
