apiVersion: github.as-code.io/v1
kind: ClusterToken
metadata:
  labels:
    app.kubernetes.io/name: clustertoken
    app.kubernetes.io/instance: clustertoken-sample
    app.kubernetes.io/part-of: github-token-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: github-token-manager
  name: clustertoken-sample
spec:
  secret:
    namespace: default
  permissions:
    metadata: read
  refreshInterval: 10m
