apiVersion: github.as-code.io/v1
kind: Token
metadata:
  labels:
    app.kubernetes.io/name: token
    app.kubernetes.io/instance: token-sample
    app.kubernetes.io/part-of: github-token-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: github-token-manager
  name: token-sample
spec:
  permissions:
    metadata: read
  refreshInterval: 10m
