---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: {{ include "chart.fullname" . }}
    control-plane: manager
  name: {{ include "chart.namespace" . }}
