---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ include "chart.fullname" . }}
    app.kubernetes.io/instance: manager-metrics-service
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: {{ include "chart.fullname" . }}
    control-plane: manager
  name: {{ include "chart.fullname" . }}-metrics-service
spec:
  {{- $service := .Values.service }}
  type: {{ .Values.service.type }}
  ports:
    {{ $service.ports | toYaml | nindent 4 }}
  selector:
    control-plane: manager
